//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v6.5.3, CSLA Templates: v4.0.0.0, CSLA Framework: v4.5.x.
//       Changes to this template will not be lost.
//
//     Template: Criteria.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;

namespace Lemon.Model
{
    public partial class AccountCriteria
    {
    }
}